### ISSUE TITLE
Craft - This time for realz

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-java#1063]
We've been had such task a few times in the last year. But What if this time we actually did it? :)

- [x] CI zips up all artifacts (done in #950)
- [x] Push to CI should create an artifact named after the build #1062
- [ ] craft needs a new target called `maven` that will upload the artifacts. See #952
- [ ] Signing, which today is done automatically by sign-and-deploy-file
- [ ] ZIP files don't contain debug symbols (we need to zip them too so we can upload debug symbols from sentry itself)
- [ ] When removing the Bintray plugin, we'd need to integrate the maven-publish plugin to write the mandatory fields in the pom file

Get the zips created through (https://github.com/getsentry/sentry-java/issues/950) and add as a GH actions artifact as per craft requirements:
https://github.com/getsentry/craft#using-github-actions-with-github-artifact-provider

Create the craft 'bintray' target, which will invoke Maciej's task:
https://github.com/getsentry/sentry-java/issues/951
The target will publish via API: https://github.com/getsentry/sentry-java/issues/952

**Comment by bruno-garcia** [comment]
For what 'sdk.name's are used and release registry:

https://github.com/getsentry/sentry-release-registry/issues/34

https://github.com/getsentry/sentry-docs/pull/2969

**Comment by marandaneto** [comment]
I've added new checkboxes to the list

**Comment by marandaneto** [comment]
sigh, https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/
we'd need to revisit this and now we have a hard deadline

**Comment by marandaneto** [comment]
depends on https://github.com/getsentry/sentry-java/issues/1490

**Comment by marandaneto** [comment]
fianlly https://github.com/getsentry/sentry-java/blob/main/.craft.yml

**Comment by bruno-garcia** [comment]
I'll buy a moët now!

Thanks everyone 🍾
