### ISSUE TITLE
Performance tracking doesn't work on android os version 24

### ISSUE THREAD

**Issue by wangtao7c0** [getsentry/sentry-java#1401]
_Platform:_
- [x]  Android -> If yes, which Device API (and compileSdkVersion/targetSdkVersion/Build tools) version?
- [ ]  Java -> If yes, which Java (and sourceCompatibility/targetCompatibility) version?
- [ ]  Kotlin -> If yes, which Kotlin (and jvmTarget) version?
- [ ]  NDK -> If yes, which NDK/CMake version?
- [ ]  React-Native -> If yes, which version?
- [ ]  Timber -> If yes, which version?
- [ ]  Log4j2 -> If yes, which version?
- [ ]  Logback -> If yes, which version?
- [ ]  Spring -> If yes, which version?

_IDE:_
- [x]  Android Studio -> If yes, which version?
- [ ]  IntelliJ -> If yes, which version?
- [ ]  Other -> If yes, which one?

_Build system:_
- [x]  Gradle -> If yes, which version?
- [ ]  Buck -> If yes, which version?
- [ ]  Bazel -> If yes, which version?
- [ ]  Maven -> If yes, which version?
- [ ]  Other -> If yes, which one?

_Android Gradle Plugin:_
- [x]  Yes -> If yes, which version?
- [ ]  No

_Sentry Android Gradle Plugin:_
- [x]  Yes -> If yes, which version?
- [ ]  No

_Proguard/R8:_
- [ ]  Enabled
- [x]  Disabled

_Platform installed with:_
- [ ] JCenter
- [ ] Bintray
- [x] Maven Central
- [ ] Manually

The version of the SDK:
**4.3.0**

---
I have the following issue:

Performance tracking doesn't work on android os version 24.

I guess the reason is some method in interface ActivityLifecycleCallbacks is added from android os version 29, 
so os version less than 29 don't work.

  @Override
  public synchronized void onActivityPostResumed(final @NonNull Activity activity) {
    // this should be called only when onResume has been executed already, which means
    // the UI is responsive at this moment.
    stopTracing(activity, options.isEnableActivityLifecycleTracingAutoFinish());
  }

  @Override
  public synchronized void onActivityPreCreated(
      final @NonNull Activity activity, final @Nullable Bundle savedInstanceState) {
    // if activity has global fields being init. and
    // they are slow, this won't count the whole fields/ctor initialization time, but only
    // when onCreate is actually called.
    startTracing(activity);
  }

https://developer.android.com/reference/android/app/Application.ActivityLifecycleCallbacks#onActivityPreCreated(android.app.Activity,%20android.os.Bundle)

**Steps to reproduce:**
- Step

**Actual result:**
- Actual

**Expected result:**
- make it compatible with lower api level

**Comment by marandaneto** [comment]
@wangtao7c0 thanks for reporting, going to check this out

**Comment by marandaneto** [comment]
@wangtao7c0 could you inform us of the compileSdkVersion/targetSdkVersion/Build tools versions? thanks

**Comment by wangtao7c0** [comment]
> @wangtao7c0 could you inform us of the compileSdkVersion/targetSdkVersion/Build tools versions? thanks
        compileSdkVersion     : 29,
        buildToolsVersion       : '29.0.2',
        targetSdkVersion        : 26,

**Comment by marandaneto** [comment]
thanks @wangtao7c0 we're going to cut a release soon.

**Comment by wangtao7c0** [comment]
> thanks @wangtao7c0 we're going to cut a release soon.

you are welcome.  best wishes for sentry !
