### ISSUE TITLE
sentry-debug-meta.properties not present when the apk is built via bitrise

### ISSUE THREAD

**Issue by Shilaghae** [getsentry/sentry-java#1461]
_Platform:_
- [x]  Android -> compileSdkVersion= 29
                             targetSdkVersion= 29
                             minSdkVersion 23
                             gradle-distribution=6.5-all 
                             com.android.tools.build:gradle:4.1.3
                             io.sentry:sentry-android-gradle-plugin:1.7.36
                             io.sentry:sentry-android:4.3.0
- [x]  Kotlin -> 1.4.31 and jvmTarget 1.8

_IDE:_
- [x]  Android Studio -> 4.1.3
- [x]  Bitrise

_Build system:_
- [x]  Gradle -> See Android section

_Android Gradle Plugin:_
- [x ]  Yes -> See android section

_Sentry Android Gradle Plugin:_
- [x]  Yes -> See Android section

_Proguard/R8:_
- [x]  Enabled

_Platform installed with:_
- [x] JCenter

The version of the SDK:
**4.3.0** 

---
I have the following issue:
When I build the apk locally I the mapping file for proguard is correctly uploaded on sentry, I use the sentry gradle plugin with autoUpload enabled, and I can also see that the io.sentry.ProguardUuids is in the intermediates/merge_assets/release or qa/out/sentry-debug-meta.properties while when I build the apk via bitrise the file is not present in the apk generated and I get:

```
> Task :app:stripQaDebugSymbols
Unable to strip the following libraries, packaging them as they are: libsentry-android.so, libsentry.so.

> Task :app:minifyQaWithR8
R8: Missing class: org.conscrypt.ConscryptHostnameVerifier

> Task :app:persistSentryProguardUuidsForQaQa
> compressing mappings
> uploading mappings
> Uploaded a total of 0 new mapping files
```

which makes me think that the sentry plugin works, I am wondering if bitrise create a different structure of the project and maybe the merge_assets are under a different folder. Any suggestion about how to solve this problem? The end result is that I can't deobfuscate in sentry and I also get the warning **Some frames appear to be minified. Did you configure the Sentry Gradle Plugin?**
In Bitrise I use the common **Android Build Step 0.10.3**

Cheers.

**Comment by marandaneto** [comment]
thanks for the report, probably a dup of https://github.com/getsentry/sentry-android-gradle-plugin/issues/37 please try the workaround written in the GH issue or try our latest gradle plugin version (alpha).
