### ISSUE TITLE
Include unfinished spans in transactions

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-java#1690]
When a transaction is finished, the SDK tries to send the data to Sentry.
If an open Span (one that was not finished) exist in that transaction, the SDK removes that span before sending the data to Sentry.

That was done because [Sentry will discard the transaction if unfinished spans are included](https://github.com/getsentry/relay/blob/569678659bac656d6c4a6edcbdf3381677b5eaa2/relay-general/src/store/transactions.rs#L110-L130). More context on this thread: https://github.com/getsentry/develop/issues/274

An alternative solution used by the JavaScript SDK is to complete those spans with the timestamp of the finishing transaction and setting the status to `timeline_exceeded`. We should align with this approach as it shows something was going on even though it wasn't completed during the transaction.

On:

```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/sentry-cocoa/issues/1303
- [ ] https://github.com/getsentry/sentry-dotnet/issues/1182
- [ ] https://github.com/getsentry/relay/issues/1244
- [ ] https://github.com/getsentry/sentry-dotnet/issues/1182
```

**Comment by marandaneto** [comment]
`deadline_exceeded` the status is called

**Comment by bruno-garcia** [comment]
Reopening as the goal is to stop modifying the span status (or removing it for that matter) if a span is not finished.
Relay will take care of it: https://github.com/getsentry/relay/issues/1244
Related .NET issue: https://github.com/getsentry/sentry-dotnet/issues/1182

**Comment by markushi** [comment]
Let's remove the hack of setting the `deadline_exceeded` status and just send the span as-is.

**Comment by markushi** [comment]
Closing this one in favor of the follow up meta ticket https://github.com/getsentry/team-mobile/issues/128
