### ISSUE TITLE
Java SDK basic OTEL Support

### ISSUE THREAD

**Issue by adinauer** [getsentry/sentry-java#2327]
### Description

More details tbd

Our plan is to create a `SpanProcessor` (for sending spans to Sentry) as well as probably a `TextMapPropagator` (for dealing with tracing across systems).

We'll probably also need to provide an agent `JAR` for people to auto instrument their applications.

There may be problems with initializing Sentry in combination with the agent, needs investigation.

Implementing it should address https://github.com/getsentry/sentry-java/issues/1348 .

Here's issues on other SDKs implementing OTEL support:
- https://github.com/getsentry/sentry-ruby/issues/1907
- https://github.com/getsentry/sentry-python/issues/1687
- https://github.com/getsentry/sentry-javascript/issues/6000
- https://github.com/getsentry/sentry-go/issues/486

### Accessing the initialized `Sentry` instance of the target application from the OTEL Java Agent

Asked on [OTEL GH](https://github.com/open-telemetry/opentelemetry-java-instrumentation/discussions/7042) and got some suggestions:

#### Use reflection
This would require us to perform every interaction with Sentry using reflection, not just retrieving the instance but every invocation which would lead to very difficult maintenance and brittle code

#### Add `Sentry` to the bootstrap classloader
so the same instance can be accessed from the target application and the OTEL Java Agent: This requires us to create our own custom distro of the OTEL Java Agent as shown in [their samples](https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/examples/distro). We first tried producing an agent JAR with `SpanProcessor` added as extension but that didn't allow us to add to the bootstrap classloader.

## TODOs

- [x] [Merge feature into `main`](https://github.com/getsentry/sentry-java/pull/2344)
- [x] Release
- [x] [Document](https://github.com/getsentry/sentry-docs/pull/5968)
- [x] [Create new modules for OTEL](https://github.com/getsentry/sentry-java/pull/2345)
- [x] Add new modules to release registry
- [x] [Add `instrumenter` to options and make `startTransaction` and `createChild` no-op if the `instrumenter` performing the operation does not match the configured one.](https://github.com/getsentry/sentry-java/pull/2349)
- [x] Implement [`SpanProcessor`](https://github.com/getsentry/sentry-java/pull/2357)
- [x] [Add otel to context](https://github.com/getsentry/sentry-java/pull/2361)
- [x] [Implement `TextMapPropagator`](https://github.com/getsentry/sentry-java/pull/2380)
- [x] [Allow configuring Sentry when only using the Java Agent so it's not needed in the target application](https://github.com/getsentry/sentry-java/pull/2386)
- [x] [Make sure `null` classloader (i.e. bootstrap classloader) doesn't cause issues](https://github.com/getsentry/sentry-java/pull/2386)
- [x] https://github.com/getsentry/sentry-java/issues/2376
- [x] [Add logging to `SentrySpanProcessor`, `SentryPropagator` etc.](https://github.com/getsentry/sentry-java/pull/2425)
- [x] [Add Sentry OTEL Java Agent](https://github.com/getsentry/opentelemetry-demo/pull/15) to OTEL demo
- [x] [Upgrade to latest OTEL release(s)](https://github.com/getsentry/sentry-java/pull/2420)
- [x] [Add automated tests for OTEL](https://github.com/getsentry/sentry-java/pull/2401)
- [x] Add README to `sentry-opentelemetry` modules
- [x] Use `HubAdapter` instead of `Sentry`
- [x] [Do not override default exporter config but rather document how to get rid of log spam if only using Sentry without OTEL exporter](https://github.com/getsentry/sentry-java/pull/2408)
- [x] [Link errors to transactions created via OTEL](https://github.com/getsentry/sentry-java/pull/2418)
- [x] [Make it possible to disable auto init in Java Agent so the target application can still use ENV vars and properties file for init without triggering auto init](https://github.com/getsentry/sentry-java/pull/2410)

**Comment by dalbani** [comment]
I've looked at the documentation and through the code, but I couldn't find an answer to this simple question: say that I'm using the Sentry OpenTelemetry Java agent, what am I supposed to see on my Sentry dashboard?
What gets actually pushed there when `OTEL_TRACES_EXPORTER=none` and `OTEL_METRICS_EXPORTER=none`?

To give some context, I'm trying to instrument an off-the-shelf application (Keycloak to be precise) with the Java agent, with the goal of seeing generated exceptions on my Sentry dashboard. Is this use case supposed to be (already) possible?

**Comment by adinauer** [comment]
Hello @dalbani. We're not using exporters to send the Spans to Sentry but instead rely on a SpanProcessor which converts OpenTelemetry Spans into Sentry Transactions / Spans. I haven't tried instrumenting keycloak myself and I don't know what underlying frameworks (if any) it uses so I can't say for sure whether something would show up. I wasn't able to find any direct instrumentation for it in the OpenTelemetry repository (https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/instrumentation). If it does work you should be able to see transactions in the Sentry UI under "Performance".

**Comment by adinauer** [comment]
I guess you should at least be able to see some database queries showing up in Sentry.

**Comment by adinauer** [comment]
Yes for now you'd have to rely on one of the logging integrations (logback, log4j2, jul) for capturing errors. We have https://github.com/getsentry/sentry-java/issues/2480 to explore capturing errors via the Java Agent. I guess we'd have to find the place where unhandled exceptions are caught for every framework we want to support and capture it there. We don't have plans for doing this for things like keycloak though. It would be for commonly used frameworks.

**Comment by dalbani** [comment]
For the record, I've stumbled upon an extension for Quarkus (the framework Keycloak is based on) for an integration with Sentry: https://github.com/quarkiverse/quarkus-logging-sentry. [*]
I just need to find out how to properly use in my setup and it should do exactly what I want.

[*] It's your call obviously, but having an official support for Quarkus would be great, I think.

**Comment by adinauer** [comment]
@dalbani thanks for the feedback. We've had multiple requests for a quarkus integration (e.g. https://github.com/getsentry/sentry-java/issues/2254). We may look into adding it at some point but it's not on our immediate roadmap (yet).
