### ISSUE TITLE
[Android] Improve Onboarding

### ISSUE THREAD

**Issue by smeubank** [getsentry/sentry-java#2802]
With learnings from the modal screen for framework selection (vanilla platforms, JS, Node, and Python) , toggles for providing users with snippets they need based on the products they want. We want to improve Android onboarding and adoption as well. To ensure developers get all the bell's and whistles turned on from performance and profiling, to ensuring we can be in their CI and build processes so they have quality source code context for each release to get readable stack traces and be able to link to their source code.

```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/sentry/issues/51792
- [ ] https://github.com/getsentry/sentry-docs/issues/7294
- [ ] https://github.com/getsentry/sentry-wizard/issues/316
- [ ] https://github.com/getsentry/sentry-java/issues/2877
```

**Comment by smeubank** [comment]
@romtsn I am assigning these to you as the DRI, I don;t know exactly how mobile like to get things into backlog. I will let you handle

**Comment by romtsn** [comment]
> @romtsn I am assigning these to you as the DRI, I don;t know exactly how mobile like to get things into backlog. I will let you handle

that's good 👍
