### ISSUE TITLE
Track app start data

### ISSUE THREAD

**Issue by markushi** [getsentry/sentry-java#3035]
## Description
Track app start data for cold/warm/hot app starts.

Besides tracking the overall duration ([P-Y provides a great introduction for Android here](https://blog.p-y.wtf/tracking-android-app-launch-in-production)) it would be even more valuable to see which components contribute to the app start.

* Track `ContentProvider.onCreate` calls (using bytecode instrumentation)
* Track `Application.onCreate` call (using bytecode instrumentation)
* Track Activity.onCreate/onStart/onResume calls, note: there could be multiple Activities until the first frame is drawn (known as [Trampoline Activities](https://marcellogalhardo.dev/posts/2023/trampoline-activities/))

![image](https://github.com/getsentry/team-mobile/assets/1411808/3e9c7e25-813d-4616-a984-14218fd9119a)

Related discussion: https://github.com/getsentry/team-sdks/issues/22

Slack-Channel:
#discuss-mobile-starfish

```[tasklist]
### Tasks
- [x] Track overall app start time
- [x] Android: Instrument Application and ContentProvider
- [x] Android: Track Activities
- [ ] Android: Collect Room method names to group db.sql.room spans better
```

**Comment by kahest** [comment]
@markushi FYI I transferred this to https://github.com/getsentry/sentry-java and adapted the title to reflect that this is specific for Android. We'll create platform issues for other SDKs if needed.
