### ISSUE TITLE
Version 1.0.0 and rename planning

### ISSUE THREAD

**Issue by bretthoerner** [getsentry/sentry-java#376]
We just released 8 but there are some breaking changes we'd like to make... 😬 ~~If we're sticking to semver-ish then we need to bump to 9.~~ This is a good chance to rename to `io.sentry:sentry-java:1.0.0`

- [x] Rename package to `io.sentry` #377 
- [x] Rename artifacts to `sentry-java` (etc) #377 
- [x] Change version to `1.0.0` #377 
- [x] Move all static Raven access to its own class (Rename `Raven` to `SentryClient` and use `Sentry` for static access) #378 
- [x] Rename `SENTRY_SENTRYFACTORY` and related (formerly `SENTRY_RAVENFACTORY`) to `SENTRY_FACTORY`
- [x] Land React Native support branch which includes changes to stack interface #368 
- [x] Add user to context
- [x] Add way to set release/env/tags/etc for static access (like appenders do)
- [x] Remove base64 encoding -> Use simple gzipped JSON #382 
- [x] Allow configuration of release/env/etc on SentryClient itself.
- [x] Add release/env/serverName etc to DSN.
- [x] Remove `SentryAndroid` in favor of single static class (`Sentry`)
- [x] Configure appenders via a properties file
- [x] Change eventBuilderHelpers to list. #402 
- [x] Drop misuse of `ServiceLoader` in favor of `Class.forName(klass).newInstance()`?
- [x] Improve NOOP DSN log.
- [x] Re-check documentation for 1.0 changes

**Comment by bretthoerner** [comment]
Actually, @mitsuhiko think we should rename to Sentry and make some big fixes, I agree.

We can go to 1.0 on Sentry, and move the appender config into what is now Raven so it's not all duplicated and so Android can use it (release, environment, tags, etc).

**Comment by awitherow** [comment]
Well done @bretthoerner !
