### ISSUE TITLE
[Epic] ANR improvements

### ISSUE THREAD

**Issue by kahest** [getsentry/sentry-java#3934]
### Description

Let's collect known issues here that we can tackle to improve overall quality and actionability of ANRs.

```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/sentry-java/issues/3654
- [ ] https://github.com/getsentry/sentry-java/issues/3287
- [ ] https://github.com/getsentry/sentry-java/issues/2801
- [ ] https://github.com/getsentry/sentry-java/issues/3806
- [ ] https://github.com/getsentry/sentry-java/issues/3837
```

**Comment by Angelodaniel** [comment]
Hey @stephanie-anderson @christophaigner wanted to check if this is still somewhere on your radar as this was from Karl back then. It would greatly improve our ANR reporting! 
Can we link Linear to it?

**Comment by christophaigner** [comment]
Hey @Angelodaniel, thanks for flagging - this is on our radar and there is an internal Linear issue for it ([ANDROID-96](https://linear.app/getsentry/issue/ANDROID-96/android-anr-improvements)). We will merge this with another initiative which is currently ongoing.

**Comment by markushi** [comment]
(Don't worry, this effort is being tackled as part of the https://linear.app/getsentry/project/anr-improvements-android-1b00822b7a4a/overview project)
